Session id with cloudflare
Stickymaddness/Procurement pull request #902
Opened 2018-12-14 04:40 UTC by thailyn

This is a rather janky fix so we can log in while using Session ID.  The user must provide his user agent, and the values of two cloud flare cookies, on the login window.  The first, "CloudFlare ID" (the cookie named `__cfduid`), appears to be pretty static.  However, the second, "CloudFlare PW" (the cookie named `cf_clearance`), appears to expire after about an hour, and it also appears it can not be reused after a failed login attempt.  The user must navigate to `https://www.pathofexile.com/login` in his browser to force refreshing the `cf_clearance` cookie.  I haven't tried keeping Procurement open for a while and seeing if that cookie invalidates after a while; the user might end up needing to re-log-in every so often.

I personally think the additions to the UI are awful, and would love for them to be redone by a more loving hand, but... it works.

Partially addresses #901.

2018-12-14 10:29 UTC, aydjay requested changes
Fix works, small amendments required but we should absolutely expedite this into a release to restore Procurement to a working state.

2018-12-14 15:09 UTC, thailyn commented on Procurement/ViewModel/LoginWindowViewModel.cs
> +                OnPropertyChanged("UserAgent");
Yeah, the new base class is probably a good idea, but outside the cope of this PR.

2018-12-14 15:09 UTC, thailyn commented on POEApi.Transport/HttpTransport.cs
Done.

2018-12-14 15:10 UTC, thailyn commented on Procurement/View/LoginView.xaml
> +                <TextBox Name="txtUserAgent" Text="{Binding UserAgent}" Grid.Row="3" Grid.Column="1"
Done.

2018-12-14 15:34 UTC, thailyn commented on POEApi.Transport/CachedTransport.cs
Got it.  Initially I had this property not forwarding the user agent, which was wrong, and I forgot to remove the backing variable after making that switch.

2018-12-18 10:13 UTC, aydjay commented
This can be closed with #903's merging

2018-12-18 11:19 UTC, closed without merging